<?php
    $title = 'My albums';
    $this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <br>
    <a class="btn btn-success" href="<?= $this->url('album', ['action' => 'add']) ?>" role="button"> Add new album </a>
</p>

<table class="table table-success table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        <?php foreach ($albums as $album) : ?>
            <tr>
                <td><?= $this->escapeHtml($album->title) ?></td>
                <td><?= $this->escapeHtml($album->artist) ?></td>
                <td>
                    <a class="btn btn-info" href="<?= $this->url('album', ['action' => 'show', 'id' => $album->id]) ?>" role="button"> Show </a>
                    <a class="btn btn-warning" href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>" role="button"> Edit </a>
                    <a class="btn btn-danger" href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>" role="button"> Delete </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>